### ISSUE TITLE
Cannot import ol-react

### ISSUE THREAD

**Issue by caiohamamura** [richardhills/ol-react#1]
I think there is some error in the configuration file for this package. Since npm didn't create /lib/index.js as specified in package.json, so it cannot be imported at all.

**Comment by richardhills** [comment]
Hi @caiohamamura ,

Thanks for pointing this out. I hope it's fixed in the latest release, 0.1.3 on npm - let me know how you get on.

**Comment by caiohamamura** [comment]
Great work by the way, I've read the library's code and it is really neat. If you post a ToDo list I'd be glad to help.
