### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Morwenn** [richardhills/ol-react#8]
Hi, you project looks promising, but it lacks a license, which generally means (quoting GitHub FAQ) that *the default copyright laws apply [...]; you retain all rights to your source code and nobody else may reproduce, distribute, or create derivative works from your work*, so it's legally hard to actually do anything with your project.

Is this really your intent?

Thanks in advance :)

**Comment by richardhills** [comment]
Hi Morwenn,

Thanks for pointing this out. I've put it under MIT license so you don't need to worry about a civil case from me.

What are you hoping to use ol-react for? Cheers,

Richard

**Comment by Morwenn** [comment]
Hi, thanks for taking the time to update the license.

We had a new project at work, and decided at some point to use React and OpenLayers 3 among other libraries, without really knowing how to bind them and your library looked like an interesting base to start working. Well, long story short, since there was no license we didn't use it, but I guess it could help us to solve some problems in a near future.

Anyway, thanks again! :)
